# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carimage',
            name='car_image_url',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
