# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_carimage_car_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_accident',
            field=models.CharField(max_length=100),
        ),
    ]
