# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_auto_20180710_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_company_name',
        ),
        migrations.AlterField(
            model_name='car',
            name='car_accident',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_category',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_color',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_fuel',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_make',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_transmission',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_vnumber',
            field=models.CharField(max_length=1000),
        ),
    ]
