# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_auto_20180710_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_km',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_vin',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
