# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_auto_20180710_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
