# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_auto_20180711_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimage',
            name='car_image_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_image_car_key', to='car.Car'),
        ),
    ]
